# Generated by Django 4.2.28 on 2026-02-05 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('os_version', models.IntegerField(blank=True, null=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.fleet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fleet',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_fleet_per_user'),
        ),
    ]
